---
downloads: ~/.ansible-downloads/

configure_osx: yes

dotfiles_repo: https://github.com/ramiro314/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Deployment/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - chromedriver
  - docker
  - docker-compose
  - docker-machine
  - git
  - highlight
  - pyenv
  - pyenv-virtualenv
  - sqlite
  - unar
  - zsh
  - zsh-completions

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - android-file-transfer
  - anki
  - caffeine
  - calibre
  - dash
  - docker
  - dropbox
  - evernote
  - filezilla
  - folx
  - google-chrome
  - iterm2
  - java
  - kindlegen
  - messenger
  - parallels-desktop
  - pycharm
  - qlcolorcode
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - quicklook-csv
  - quicklook-json
  - skype
  - slack
  - spectacle
  - steam
  - the-unarchiver
  - virtualbox
  - vlcaudacity
  - webpquicklookbartender
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 443987910, name: "1Password" }
  - { id: 585829637, name: "Todoist" }
  - { id: 557168941, name: "Tweetbot" }
  - { id: 497799835, name: "Xcode" }
mas_email: "ramiro.314@gmail.com"
mas_password: ""
