---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - ramiro314.homebrew
    - ramiro314.dotfiles
    - name: ramiro314.mas
      when: mas_installed_apps

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/sudoers.yml
      when: configure_sudoers

    - include: tasks/terminal.yml
      when: configure_terminal

    - include: tasks/osx.yml
      when: configure_osx
